### ISSUE TITLE
Error, white screen, and exiting code 2

### ISSUE THREAD

**Issue by justanthonyofficial** [HydroProtocol/hydro-scaffold-dex#76] opened 2020-02-22 18:13 UTC
Help with a mistake. Here is such an error and a white screen instead of the exchange
![photo_2020-02-22_18-13-16](https://user-images.githubusercontent.com/56980860/75097125-5624ce80-55d1-11ea-984d-6e3e7ca48818.jpg)

**Comment by MonarthS** [comment] 2020-04-16 04:20
#80

**Comment by MonarthS** [comment] 2020-04-16 04:21
Duplicate of #80

**Comment by tstyle11** [comment] 2020-08-11 17:18
Closing as fixed

**Closed by tstyle11** 2020-08-11 17:18 UTC
